# Generated by Django 5.1.1 on 2024-09-18 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
    ]
